# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xp4bqP8Ie5vBynXoIrmcuWUWJfGDvcs
"""

# 1. Install Library
!pip install mlflow dagshub

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
import os

# --- KONFIGURASI MANUAL (ANTI ERROR) ---
DAGSHUB_USERNAME = "wisinau"
DAGSHUB_REPO_NAME = "Heart-Failure-Tracking"
# Pastikan token tetap di dalam tanda kutip
DAGSHUB_TOKEN = "76fe4c9242852a6125f39c059bc538163d4a236e"

# --- PERBAIKAN DI SINI ---
# Gunakan variabel yang sudah dibuat di atas
os.environ["MLFLOW_TRACKING_USERNAME"] = DAGSHUB_USERNAME
os.environ["MLFLOW_TRACKING_PASSWORD"] = DAGSHUB_TOKEN

# Set Tracking URI Manual
mlflow.set_tracking_uri(f"https://dagshub.com/{DAGSHUB_USERNAME}/{DAGSHUB_REPO_NAME}.mlflow")

# --- LOAD DATA ---
def load_data():
    # Cek keberadaan file
    if not os.path.exists("X_train.csv"):
        print("[WARNING] File X_train.csv tidak ditemukan. Pastikan sudah upload!")
        return None, None, None, None

    X_train = pd.read_csv("X_train.csv")
    y_train = pd.read_csv("y_train.csv").values.ravel()
    X_test = pd.read_csv("X_test.csv")
    y_test = pd.read_csv("y_test.csv").values.ravel()
    return X_train, y_train, X_test, y_test

def main():
    print(f"[INFO] Tracking ke: {mlflow.get_tracking_uri()}")
    mlflow.set_experiment("Eksperimen_Aditya_DagsHub_Fix")

    X_train, y_train, X_test, y_test = load_data()

    if X_train is None:
        return # Stop jika data tidak ada

    with mlflow.start_run(run_name="RandomForest_Manual_Auth"):
        # Training
        print("[INFO] Memulai training...")
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X_train, y_train)

        # Evaluasi
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average='macro')

        print(f"Metrics: Acc={acc:.4f}, F1={f1:.4f}")

        # Logging
        mlflow.log_param("n_estimators", 100)
        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("f1_score", f1)
        mlflow.sklearn.log_model(model, "model_rf")

        print("\n[SUCCESS] Berhasil kirim ke DagsHub!")
        print(f"Cek Dashboard di: https://dagshub.com/{DAGSHUB_USERNAME}/{DAGSHUB_REPO_NAME}")

if __name__ == "__main__":
    main()

# Cell 1: Nyalakan Server di Background
get_ipython().system_raw("mlflow ui --port 5000 &")

print("MLflow Server sedang berjalan di background pada port 5000...")

# Cell 2: Script Modelling Anda
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
import os

# --- KONFIGURASI SESUAI GAMBAR ---
# Sekarang baris ini akan BERHASIL karena server sudah nyala di Langkah 1
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

# --- LOAD DATA ---
def load_data():
    if not os.path.exists("X_train.csv"):
        print("[WARNING] File X_train.csv tidak ditemukan. Pastikan sudah upload!")
        return None, None, None, None

    X_train = pd.read_csv("X_train.csv")
    y_train = pd.read_csv("y_train.csv").values.ravel()
    X_test = pd.read_csv("X_test.csv")
    y_test = pd.read_csv("y_test.csv").values.ravel()
    return X_train, y_train, X_test, y_test

def main():
    print(f"[INFO] Tracking URI diset ke: {mlflow.get_tracking_uri()}")

    mlflow.set_experiment("Eksperimen_Aditya_Localhost")

    X_train, y_train, X_test, y_test = load_data()

    if X_train is None: return

    with mlflow.start_run(run_name="RandomForest_Run"):
        print("[INFO] Memulai training...")
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average='macro')

        print(f"Metrics: Acc={acc:.4f}, F1={f1:.4f}")

        mlflow.log_param("n_estimators", 100)
        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("f1_score", f1)
        mlflow.sklearn.log_model(model, "model_rf")

        print("\n[SUCCESS] Run selesai! Artefak tersimpan di Localhost Server.")

if __name__ == "__main__":
    main()